return {
 ["name:Inter Bold Italic:mode=node;script=latn;language=dflt;#786434"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-BoldItalic.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;#786434"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#1034840"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#1287341"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#310452"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#517420"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#566574"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#620904"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#745084"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#776130"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Bold:mode=node;script=latn;language=dflt;+tlig;#827872"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Bold.otf", false },
 ["name:Inter Italic:mode=node;script=latn;language=dflt;#786434"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Italic.otf", false },
 ["name:Inter Italic:mode=node;script=latn;language=dflt;+tlig;#517420"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Italic.otf", false },
 ["name:Inter Italic:mode=node;script=latn;language=dflt;+tlig;#566574"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Italic.otf", false },
 ["name:Inter Italic:mode=node;script=latn;language=dflt;+tlig;#620904"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Italic.otf", false },
 ["name:Inter Italic:mode=node;script=latn;language=dflt;+tlig;#745084"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Italic.otf", false },
 ["name:Inter Regular:mode=node;#786430"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;#786434"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;#786434"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#1034840"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#1287341"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#284581"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#310452"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#413936"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#517420"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#566574"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#620904"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#745084"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#776130"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#827872"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;#894101"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter Regular:mode=node;script=latn;language=dflt;+tlig;+smcp;#517420"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
 ["name:Inter#786431"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/inter/Inter-Regular.otf", false },
}